# Generated by Django 4.2.2 on 2023-06-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_reservation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_articles', to='hospital.user')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_articles', to='hospital.user')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspect_articles', to='hospital.user')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate_articles', to='hospital.user')),
            ],
        ),
    ]
