# Generated by Django 4.2.2 on 2023-06-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_user_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
