# Generated by Django 4.2.2 on 2023-06-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_mbti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mbti',
        ),
    ]
